### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by bitsofparag** [TosinAF/TAWebViewController#1]
Does `TAWebViewController`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller built over the standard iOS Webkit library?

**Comment by TosinAF** [comment]
it's just a view controller built over the standard iOS Webkit library

Sent from Outlookhttp://taps.io/outlookmobile
